default:	cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoardMem.java
	javac cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoardMem.java

run:	cpsc2150/extendedConnectX/GameScreen.java cpsc2150/extendedConnectX/GameBoard.java cpsc2150/extendedConnectX/AbsGameBoard.java cpsc2150/extendedConnectX/BoardPosition.java cpsc2150/extendedConnectX/IGameBoard.java cpsc2150/extendedConnectX/GameBoardMem.java
	java cpsc2150/extendedConnectX/GameScreen

clean:
	rm -f cpsc2150/extendedConnectX/*.class

