default: cpsc2150/sets/ArraySet.java cpsc2150/sets/CharacterSetApp.java cpsc2150/sets/ISet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java
	javac cpsc2150/sets/ArraySet.java cpsc2150/sets/CharacterSetApp.java cpsc2150/sets/ISet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java

run: cpsc2150/sets/ArraySet.java cpsc2150/sets/CharacterSetApp.java cpsc2150/sets/ISet.java cpsc2150/sets/ListSet.java cpsc2150/sets/SetAbs.java
	java cpsc2150.sets.CharacterSetApp

clean:
	rm -f cpsc2150/sets/*.class
	rm -f cpsc2150/sets/*.class